version: '3'

volumes:
  postgres:

services:
    postgres:
        restart: always
        image: irobbierobinson/multi-db-postgres:latest
        build:
          context: ./
          dockerfile: Dockerfile
        volumes:
            - ./pg-db-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_ADDITIONAL_DATABASES=db,keycloak
        ports:
            - 5432:5432
        networks:
            - backend
networks:
    backend:
        driver: bridge

